
import { jsPDF } from "jspdf";

interface DocumentData {
  title: string;
  summary: string;
  sections: Array<{
    heading: string;
    body: string;
  }>;
}

export const generatePDF = async (data: DocumentData, fileName: string): Promise<void> => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - (margin * 2);
  let cursorY = 30;

  // Add Branding Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("GENERATED BY JUSTPDFIT ENTERPRISE", margin, 15);
  doc.setDrawColor(230, 230, 230);
  doc.line(margin, 18, pageWidth - margin, 18);

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(0, 0, 0);
  const splitTitle = doc.splitTextToSize(data.title.toUpperCase(), contentWidth);
  doc.text(splitTitle, margin, cursorY);
  cursorY += (splitTitle.length * 10) + 10;

  // Executive Summary
  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const splitSummary = doc.splitTextToSize(`SUMMARY: ${data.summary}`, contentWidth);
  doc.text(splitSummary, margin, cursorY);
  cursorY += (splitSummary.length * 5) + 15;

  // Horizontal Rule
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  doc.line(margin, cursorY - 5, margin + 20, cursorY - 5);

  // Sections
  data.sections.forEach((section) => {
    // Check for page overflow
    if (cursorY > 260) {
      doc.addPage();
      cursorY = 20;
    }

    // Heading
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(section.heading.toUpperCase(), margin, cursorY);
    cursorY += 8;

    // Body
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(50, 50, 50);
    const splitBody = doc.splitTextToSize(section.body, contentWidth);
    
    // Check for large section overflow
    if (cursorY + (splitBody.length * 6) > 280) {
        // Simple splitting for demonstration - better to split line by line
        const midPoint = Math.floor(splitBody.length / 2);
        const part1 = splitBody.slice(0, midPoint);
        const part2 = splitBody.slice(midPoint);
        
        doc.text(part1, margin, cursorY);
        doc.addPage();
        cursorY = 25;
        doc.text(part2, margin, cursorY);
        cursorY += (part2.length * 6) + 12;
    } else {
        doc.text(splitBody, margin, cursorY);
        cursorY += (splitBody.length * 6) + 12;
    }
  });

  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 15, 285);
    doc.text(`CONFIDENTIAL • ${new Date().toLocaleDateString()}`, margin, 285);
  }

  // Save the PDF
  const safeName = fileName.replace(/\.[^/.]+$/, "") + ".pdf";
  doc.save(safeName);
};
